# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed34ba636862d4f6cc890b391cc64128274dea515b8c25b1508dd823bf53e1fa8c00514f2ffc096f884b6869d3ca669d4bc77ec54210926e4c7734874cf82ba6

test:
  secret_key_base: d198eab86a7dc11feef4d2e5b88152125bf38e1d8908d2bfc496fc54be37ab42022953c88575f6e622961382b3cba10a2ffe29e916bfb058f6dc56b15e836528

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
